force-app/main/default/objects/ContentLinkDefault__mdt/ContentLinkDefault__mdt.object-meta.xml
<CustomObject>
    <description>Overwrite Content Link default values based on object specific rules.</description>
    <label>Content Link Default</label>
    <pluralLabel>Content Link Defaults</pluralLabel>
</CustomObject>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/CurrentShareType__c.field-meta.xml
<CustomField>
    <fullName>CurrentShareType__c</fullName>
    <description>Select the current share type the Content Link record must have to apply this rule.</description>
    <inlineHelpText>Select the current share type the Content Link record must have to apply this rule.</inlineHelpText>
    <label>Current Share Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>View</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Set by Record</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Collaborator</label>
            </value>
            <value>
                <fullName>*</fullName>
                <default>true</default>
                <label>Any</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/CurrentVisibility__c.field-meta.xml
<CustomField>
    <fullName>CurrentVisibility__c</fullName>
    <description>Select the current visibility the Content Link record must have to apply this rule.</description>
    <inlineHelpText>Select the current visibility the Content Link record must have to apply this rule.</inlineHelpText>
    <label>Current Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AllUsers</fullName>
                <default>true</default>
                <label>All Users</label>
            </value>
            <value>
                <fullName>InternalUsers</fullName>
                <label>Standard Users</label>
            </value>
            <value>
                <fullName>SharedUsers</fullName>
                <label>Shared Users</label>
            </value>
            <value>
                <fullName>*</fullName>
                <label>Any</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, this rule will be processed when new Content Link Records are created</description>
    <inlineHelpText>When checked, this rule will be processed when new Content Link Records are created</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/OrderIndex__c.field-meta.xml
<CustomField>
    <fullName>OrderIndex__c</fullName>
    <description>Order in which this rule will be processed. Lower numbers are processed before higher numbers.</description>
    <inlineHelpText>Order in which this rule will be processed. Lower numbers are processed before higher numbers.</inlineHelpText>
    <label>Rule Order Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/ShareType__c.field-meta.xml
<CustomField>
    <fullName>ShareType__c</fullName>
    <description>Select the share type that will be assigned to the Content Link record. Select &#39;Do NOT Change&#39; if the value should not be assigned.</description>
    <inlineHelpText>Select the share type that will be assigned to the Content Link record. Select &#39;Do NOT Change&#39; if the value should not be assigned.</inlineHelpText>
    <label>Share Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <default>true</default>
                <label>View</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Set by Record</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Collaborator</label>
            </value>
            <value>
                <fullName>NA</fullName>
                <label>Do NOT change</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/sObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_API_Name__c</fullName>
    <description>API Name of SObject that this rule applies to. If this rule should apply to all sobjects, enter *</description>
    <inlineHelpText>API Name of SObject that this rule applies to. If this rule should apply to all sobjects, enter *</inlineHelpText>
    <label>sObject API Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/TestData__c.field-meta.xml
<CustomField>
    <fullName>TestData__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify test metadata record. Do not check for actual usage.</description>
    <inlineHelpText>Used to identify test metadata record. Do not check for actual usage.</inlineHelpText>
    <label>Test Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/TriggerContext__c.field-meta.xml
<CustomField>
    <fullName>TriggerContext__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Only execute this rule when a trigger called the default assignment method.</description>
    <inlineHelpText>Only execute this rule when a trigger called the default assignment method.</inlineHelpText>
    <label>Trigger Context Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/UserType__c.field-meta.xml
<CustomField>
    <fullName>UserType__c</fullName>
    <description>Apply this rule only when the current user type matches this value.</description>
    <inlineHelpText>Apply this rule only when the current user type matches this value.</inlineHelpText>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*</fullName>
                <label>Any</label>
            </value>
            <value>
                <fullName>Internal</fullName>
                <default>true</default>
                <label>Internal</label>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>HV</fullName>
                <label>High-Volume</label>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentLinkDefault__mdt/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <description>Select the visibility that will be assigned to the Content Link record. Select &#39;Do NOT Change&#39; if the value should not be assigned.</description>
    <inlineHelpText>Select the visibility that will be assigned to the Content Link record. Select &#39;Do NOT Change&#39; if the value should not be assigned.</inlineHelpText>
    <label>Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AllUsers</fullName>
                <default>true</default>
                <label>All Users</label>
            </value>
            <value>
                <fullName>InternalUsers</fullName>
                <label>Standard Users</label>
            </value>
            <value>
                <fullName>SharedUsers</fullName>
                <label>Shared Users</label>
            </value>
            <value>
                <fullName>NA</fullName>
                <label>Do NOT Change</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkDefault.cls
/*
 * Class to access Content Document Link default settings and apply rules to 
 * list of Content Document Link records
 * 
*/
public without sharing class ContentDocumentLinkDefault {
    @TestVisible
    private static boolean isTestRun = false;
    // Map between default metadata user type assignment and actual User Types
    private static map<string, string[]> userTypeMap = new map<string, string[]>{
        'Standard' => new string[]{'*','Internal'},
        'PowerPartner' => new string[]{'*','Partner'},
        'PowerCustomerSuccess' => new string[]{'*','Community'},
        'CustomerSuccess' => new string[]{'*','Community'},
        'Guest' => new string[]{'*','Guest'},
        'CspLitePortal' => new string[]{'*','HV'},
        'SelfService' => new string[]{'*','HV'},
        'CsnOnly' => new string[]{'*','Chatter'}
    };
    // Trigger handler
    public static void handle() {
        // Only run when not running tests, or when isTestRun is true
        if(!Test.isRunningTest()||isTestRun==true)
        	(new ContentDocumentLinkDefault(Trigger.new)).default();
    }
    
    private map<sObjectType, CdlConf> confMap = new map<sObjectType, CdlConf>{};
    private ContentDocumentLink[] cdlList;
    // Instantiate process object
    public ContentDocumentLinkDefault(ContentDocumentLink[] cdlList) {
        this.cdlList = cdlList;
        // Find all distinct linked entity object types
        map<string, sObjectType> nameMap = new map<string, sObjectType>{};
        for(ContentDocumentLink cdl: cdlList)
            if(!confMap.containsKey(cdl.LinkedEntityId.getsObjectType())) {
                string name = cdl.LinkedEntityId.getsObjectType().getDescribe().getName().toLowerCase();
                confMap.put(cdl.LinkedEntityId.getsObjectType(), new CdlConf(name));
                nameMap.put(name, cdl.LinkedEntityId.getsObjectType());
            }
        
        // Load all related configurations
        confMap.put(null, new CdlConf('*')); // Add default object configuration
        nameMap.put('*', null); // Add default object configuration
        this.loadConfig(nameMap);

    }

    // Method that assigns default values to list of COntent Document Link records
    public void default() {
        // Apply rules to each record
        for(ContentDocumentLink cdl: cdlList)
            // Try to apply specific rule, and if no matched, apply global rule
            if(confMap.containsKey(cdl.LinkedEntityId.getsObjectType()) ? confMap.get(cdl.LinkedEntityId.getsObjectType()).apply(cdl)==false : true) {
                if(confMap.containsKey(null)) // Apply global
                    confMap.get(null).apply(cdl);
            }
    }

    // Method to load all sObject related rules, include a default rule (if configured)
    private void loadConfig(map<string, sObjectType> nameObjMap) {
        // When context is trigger, include both Trigger and Non-Trigger rules, otherwise Non-trigger rules only
        boolean[] triggerContext = Trigger.isExecuting==true ? new Boolean[]{true, false}:new Boolean[]{false};
        string[] userTypes = userTypeMap.containsKey(UserInfo.getUserType()) ? userTypeMap.get(UserInfo.getUserType()):new string[]{'*'};
        // List all relevant configured rules
        for(ContentLinkDefault__mdt[] cddList: [
            Select UserType__c, TriggerContext__c, CurrentShareType__c, CurrentVisibility__c, ShareType__c, Visibility__c, sObject_API_Name__c 
            From ContentLinkDefault__mdt 
            Where 
            	Enabled__c=true 
            	And sObject_API_Name__c In:nameObjMap.keySet()
            	And TriggerContext__c In: triggerContext
            	And UserType__c In :userTypes
            	And TestData__c=:Test.isRunningTest() // Only return test records while test is running
            Order By OrderIndex__c ASC
        ]) {
            for(ContentLinkDefault__mdt cdd: cddList) {
                string soName = cdd.sObject_API_Name__c.toLowerCase();
                sObjectType soType = nameObjMap.containsKey(soName) ? nameObjMap.get(soName) : null;
                if(this.confMap.containsKey(soType)) {
                    confMap.get(soType).add(cdd);
                } else system.debug('What happened to the soType for '+soName+'?' + soType);
            }
        }
    }
	
    // Class to capture a list of rules for one object type
    // Rules are captured in order of priority
    // Apply method updates one Content Document Link record
    public without sharing class CdlConf {
        public string objectName;
        public list<CdlRule> rules = new list<CdlRule>{};
        // Instantiate configuration object
        public CdlConf(string sObjectName) {
            objectName = sObjectName;
        }
        
        // Add a new rule to list
        public void add(ContentLinkDefault__mdt cdd) {
            rules.add(new CdlRule(cdd));
        }
        
        // Iterate over all possible rules and exit at the 1st match
        public boolean apply(ContentDocumentLink cdl) {
            for(CdlRule rule: rules) {
            	if(rule.apply(cdl))
                    return true;
            }
            return false;
        }
    }
    
    // One Content Document Link modification rule
    // Apply method determines match and applies changes
	public without sharing class CdlRule {
        public string criteriaVisibility;
        public string criteriaShareType;
        public string setVisibility;
        public string setShareType;
        public CdlRule(ContentLinkDefault__mdt cdd) {
            criteriaVisibility = cdd.CurrentVisibility__c!='*'?cdd.CurrentVisibility__c:null;
            criteriaShareType = cdd.CurrentShareType__c!='*'?cdd.CurrentShareType__c:null;
            setVisibility = cdd.Visibility__c!='NA'?cdd.Visibility__c:null;
            setShareType = cdd.ShareType__c!='NA'?cdd.ShareType__c:null;
        }
        
        // Apply this rule to a Content Document Link record
        public boolean apply(ContentDocumentLink cdl) {
            if(
                (cdl.Visibility==criteriaVisibility||criteriaVisibility==null)
                && (cdl.ShareType==criteriaShareType||criteriaShareType==null)
            ) {
                cdl.Visibility = setVisibility==null ? cdl.Visibility : setVisibility;  
                cdl.ShareType = setShareType==null ? cdl.ShareType : setShareType;
                return true;
            } else
            	return false;
        }

    }
}